-- TDidacta Platform — minimal account/activity schema
-- Run in a dedicated Supabase project before enabling the public account UI.

create table if not exists public.learning_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event text not null check (
    event in (
      'lesson_opened',
      'exploration_prepared',
      'exploration_copied'
    )
  ),
  lesson_id text,
  exploration_mode text,
  occurred_at timestamptz not null default now()
);

create index if not exists learning_activity_user_time_idx
  on public.learning_activity (user_id, occurred_at desc);

create index if not exists learning_activity_event_idx
  on public.learning_activity (event, occurred_at desc);

alter table public.learning_activity enable row level security;

drop policy if exists "Users can read own learning activity" on public.learning_activity;
create policy "Users can read own learning activity"
  on public.learning_activity
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert own learning activity" on public.learning_activity;
create policy "Users can insert own learning activity"
  on public.learning_activity
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete own learning activity" on public.learning_activity;
create policy "Users can delete own learning activity"
  on public.learning_activity
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create table if not exists public.account_deletion_requests (
  user_id uuid primary key references auth.users(id) on delete cascade,
  requested_at timestamptz not null default now()
);

alter table public.account_deletion_requests enable row level security;

drop policy if exists "Users can read own deletion request" on public.account_deletion_requests;
create policy "Users can read own deletion request"
  on public.account_deletion_requests
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can create own deletion request" on public.account_deletion_requests;
create policy "Users can create own deletion request"
  on public.account_deletion_requests
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can cancel own deletion request" on public.account_deletion_requests;
create policy "Users can cancel own deletion request"
  on public.account_deletion_requests
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
