<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Teaching.CleanArchitecture.Stage04/Teaching.CleanArchitecture.Stage04.csproj" />
    <ProjectReference Include="../Teaching.CleanArchitecture.Stage04.Sqlite/Teaching.CleanArchitecture.Stage04.Sqlite.csproj" />
  </ItemGroup>

</Project>
