<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Teaching.CleanArchitecture.Stage06.Application/Teaching.CleanArchitecture.Stage06.Application.csproj" />
  </ItemGroup>

</Project>
